[package]
name = "waifu2x-ncnn-vulkan-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "^0.2.113"
image = "0.24.5"

[build-dependencies]
cmake = "^0.1.48"
